
# [ --------------------------------------------------------------------------------------- ] #
#   -= BungeeJump =-                                                                          #
#   -= Author: DevSnox =-                                                                     #
#   -= Version: 1.4.0 =-                                                                      #
#   -= Contact: E-mail: me.devsnox@gmail.com  Discord: DevSnox#7154 =-                        #
#   -= Informations:                                                                          #
#   -= Please send Errors per PM on spigotmc.org =-                                           #
#   -= When you use this Plugin please rate it on spigotmc.org =-                             #
# [ --------------------------------------------------------------------------------------- ] #


# You can find the message configuration in the messages.yml file.


# { General configuration }

#{ --------- }